server:
  port: 8080
spring:
  application:
    name: gateway-test
  cloud:
    gateway:
      routes:
      - id: neo
        uri: https://spring.io/projects/spring-cloud
        predicates:
        - Path=/spring-cloud/**
      - id: baidu
        uri: https://www.baidu.com/
        predicates:
        - Path=/baidu/**
# id 我们自定义的路由ID 保持唯一     注意前面的-,切记不能省略
# uri 目标服务地址
# predicates(断言) 路由条件 predicate接受一个输入参数,返回一个布尔值结果,如果断言为真，则路由匹配
#predicate 组合成其他复杂的逻辑
#Path前面的-，切记不能省略